// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComdQXMfKuxJOagWFxOSi5Dwa1JjF5V6k',
    appId: '1:646777919565:web:6a506ca7eecd6b310d6404',
    messagingSenderId: '646777919565',
    projectId: 'flutter-a9aef',
    authDomain: 'flutter-a9aef.firebaseapp.com',
    storageBucket: 'flutter-a9aef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1XFdXhboWkZDMUmw2xgGHXRXj3iLRL8E',
    appId: '1:646777919565:android:14da79d7ddb634c90d6404',
    messagingSenderId: '646777919565',
    projectId: 'flutter-a9aef',
    storageBucket: 'flutter-a9aef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI8s1wdWjOMOHiMZ4b7oQhUltaSI_MW4g',
    appId: '1:646777919565:ios:13e7a3368b9cd0180d6404',
    messagingSenderId: '646777919565',
    projectId: 'flutter-a9aef',
    storageBucket: 'flutter-a9aef.appspot.com',
    iosClientId: '646777919565-7nrlcru99c5vakejbl16jjd1hh4prvdl.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI8s1wdWjOMOHiMZ4b7oQhUltaSI_MW4g',
    appId: '1:646777919565:ios:13e7a3368b9cd0180d6404',
    messagingSenderId: '646777919565',
    projectId: 'flutter-a9aef',
    storageBucket: 'flutter-a9aef.appspot.com',
    iosClientId: '646777919565-7nrlcru99c5vakejbl16jjd1hh4prvdl.apps.googleusercontent.com',
    iosBundleId: 'com.light.ipssisqy2023',
  );
}
